# nixpacks.toml

[phases.setup]
nixPkgs = ['python39', 'gcc']


[phases.install]
cmds = ['python -V']

[phases.build]
dependsOn = ['setup']
cmds = ['python -m venv venv', 'source venv/bin/activate', 'python -m pip install -r requirements.txt']


[start]
cmd = 'python -m uvicorn test:app --reload --host 0.0.0.0'