# nixpacks.toml

[phases.setup]
nixPkgs = ['python311', 'gcc']


[phases.install]
cmds = ['python3 -V']

[phases.build]
dependsOn = ['setup']
cmds = ['python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt', 'python3 -m pip install uvicorn', 'python3 -m pip show uvicorn']


[start]
cmd = 'python3 -m uvicorn test:app --reload --host 0.0.0.0'