# nixpacks.toml

[phases.setup]
nixPkgs = ['python3', 'python310Packages.pip']


[phases.install]
cmds = ['sudo python3 -V']

[phases.build]
dependsOn = ['setup']
cmds = ['python3 -m venv venv', 'source venv/bin/activate', 'python3 -m pip install -r requirements.txt']


[start]
cmd = 'python3 -m uvicorn test:app --reload --host 0.0.0.0'